MODEL_2D:
  TYPE: "UNetResNet34"
  DUAL_HEAD: True
MODEL_3D:
  TYPE: "SCN"
  DUAL_HEAD: True
DATASET_SOURCE:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_usa",)
  NuScenesSCN:
#    preprocess_dir: "/data/xmw/bbox_preprocess/preprocess"
    preprocess_dir: "/data/wuyao/dataset/nuscenes/preprocess_bbox_full"  # bbox
    nuscenes_dir: "/data/xmw/nuscenes"  # only front cam images are needed
DATASET_TARGET:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_singapore",)
  VAL: ("val_singapore",)
  TEST: ("test_singapore",)
  NuScenesSCN:
#    preprocess_dir: "/data/xmw/bbox_preprocess/preprocess"
    preprocess_dir: "/data/wuyao/dataset/nuscenes/preprocess_bbox_full"  # bbox
    nuscenes_dir: "/data/xmw/nuscenes"  # only front cam images are needed
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (40000, 50000)
  MAX_ITERATION: 60000
TRAIN:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
  CLASS_WEIGHTS: [2.47956584, 4.26788384, 5.71114131, 3.80241668, 1.]
  XMUDA:
    lambda_xm_src: 1.0
    lambda_xm_trg: 0.1
    lambda_cmkd: 0.01
VAL:
  BATCH_SIZE: 8
  PERIOD: 5000

OUTPUT_DIR: "/data/wuyao/code/BFtD-xMUDA/output/usa_sing_bbox/BFtD/"
