MODEL_2D:
  TYPE: "UNetResNet34"
  DUAL_HEAD: True
MODEL_3D:
  TYPE: "SCN"
  DUAL_HEAD: True
DATASET_SOURCE:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_usa",)
  NuScenesSCN:
    preprocess_dir: "/data/wuyao/dataset/nuscenes/preprocess_seg_full"  # bbox
    nuscenes_dir: "/data/xmw/nuscenes"  # only front cam images are needed
DATASET_TARGET:
  TYPE: "NuScenesSCN"
  TRAIN: ("train_singapore",)
  VAL: ("val_singapore",)
  TEST: ("test_singapore",)
  NuScenesSCN:
    preprocess_dir: "/data/wuyao/dataset/nuscenes/preprocess_seg_full"  # bbox
    nuscenes_dir: "/data/xmw/nuscenes"  # only front cam images are needed
    pselab_paths: ("/data/wuyao/code/BFtD-xMUDA/output/usa_sing_seg/BFtD/pselab_data/train_singapore.npy",)
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000)
  MAX_ITERATION: 100000
TRAIN:
  BATCH_SIZE: 8
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
  CLASS_WEIGHTS: [2.43670589, 4.18552224, 5.66811321, 3.63882303, 1.]
  XMUDA:
    lambda_xm_src: 1.0
    lambda_xm_trg: 0.1
    lambda_pl: 0.1
VAL:
  BATCH_SIZE: 8
  PERIOD: 5000

OUTPUT_DIR: "/data/wuyao/code/BFtD-xMUDA/output/usa_sing_seg/BFtD_PL/"
